apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    config.couchbase.com/version: 2.9.0
  creationTimestamp: null
  name: couchbase-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    config.couchbase.com/version: 2.9.0
  creationTimestamp: null
  name: couchbase-operator
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - couchbase.com
  resources:
  - couchbaseclusters
  - couchbaseclusters/finalizers
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - couchbase.com
  resources:
  - couchbasereplications
  - couchbasemigrationreplications
  - couchbaseusers
  - couchbasegroups
  - couchbaserolebindings
  - couchbasebackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - couchbase.com
  resources:
  - couchbasebuckets
  - couchbaseephemeralbuckets
  - couchbasememcachedbuckets
  - couchbasescopes
  - couchbasescopegroups
  - couchbasecollections
  - couchbasecollectiongroups
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups:
  - couchbase.com
  resources:
  - couchbasebackuprestores
  verbs:
  - get
  - list
  - watch
  - delete
- apiGroups:
  - couchbase.com
  resources:
  - couchbaseautoscalers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - couchbase.com
  resources:
  - couchbaseautoscalers/status
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  - pods/status
  - services
  - persistentvolumeclaims
  # START MODIFICATION
  - pods/log
  # END MODIFICATION
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - list
  - create
  - update
  # START MODIFICATION
  - watch
  # END MODIFICATION
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
  - update
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - create
  - delete
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    config.couchbase.com/version: 2.9.0
  creationTimestamp: null
  name: couchbase-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: couchbase-operator
subjects:
- kind: ServiceAccount
  name: couchbase-operator
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    config.couchbase.com/version: 2.9.0
  creationTimestamp: null
  name: couchbase-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchbase-operator
  strategy: {}
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8383"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: couchbase-operator
    spec:
      containers:
      - args:
        - --pod-create-timeout=10m0s
        - --pod-delete-delay=0s
        - --pod-readiness-delay=10s
        - --pod-readiness-period=20s
        - --zap-log-level=info
        command:
        - couchbase-operator
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: additional-prometheus-labels
        - name: separate-cluster-name-and-namespace
          value: "true"
        image: aayushsenapati/couch:operator-arm
        imagePullPolicy: IfNotPresent
        name: couchbase-operator
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8383
          name: prometheus
        readinessProbe:
          httpGet:
            path: /readyz
            port: http
            scheme: HTTP
        resources: {}
      # START MODIFICATION
      - name: cod-sidecar
        image: aayushsenapati/couch:cod-arm
        imagePullPolicy: IfNotPresent
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 3000
          name: cod
        resources: {}
      # END MODIFICATION
      securityContext:
        runAsNonRoot: true
      serviceAccountName: couchbase-operator
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    config.couchbase.com/version: 2.9.0
  creationTimestamp: null
  name: couchbase-operator
spec:
  ports:
  - name: http-pprof
    port: 8080
    protocol: TCP
    targetPort: 8080
  # START MODIFICATION
  - name: cod
    port: 3000
    protocol: TCP
  # END MODIFICATION
  - name: http-prometheus
    port: 8383
    protocol: TCP
    targetPort: 8383
  selector:
    app: couchbase-operator

